//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NetworkSuperposition03.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_NETWORKSUPERPOSITION03_DIALOG 102
#define IDR_MAINFRAME                   128
#define ED_BASIC_STABLE_NET_SIZE        1000
#define ED_BASIC_STABLE_NET_TRANSMISSION_PROBABILITY_STRAIN_1 1001
#define ED_BASIC_STABLE_NET_TRANSMISSION_PROBABILITY_STRAIN_2 1002
#define ED_AGGREGATED_STABLE_NET_SIZE   1003
#define ED_AGGREGATED_STABLE_NET_TRANSMISSION_PROBABILITY_STRAIN_1 1004
#define ED_AGGREGATED_STABLE_NET_TRANSMISSION_PROBABILITY_STRAIN_2 1005
#define ED_BASIC_NET_WITH_FUCTUATION_SIZE 1006
#define ED_BASIC_NET_WITH_FLUCTUATION_TRANSMISSION_PROBABILITY_STRAIN_1 1007
#define ED_BASIC_NET_WITH_FLUCTUATION_TRANSMISSION_PROBABILITY_STRAIN_2 1008
#define ED_BASIC_NET_WITH_FUCTUATION_NUMBER 1009
#define ED_BASIC_NET_WITH_FLUCTUATION_FLUCTUATION 1010
#define ED_AGGREGATED_NET_WITH_FUCTUATION_SIZE 1011
#define ED_AGGREGATED_NET_WITH_FLUCTUATION_TRANSMISSION_PROBABILITY_STRAIN_1 1012
#define ED_AGGREGATED_NET_WITH_FLUCTUATION_TRANSMISSION_PROBABILITY_STRAIN_2 1013
#define ED_AGGREGATED_NET_WITH_FUCTUATION_NUMBER 1014
#define ED_POPULATION_SIZE              1015
#define ED_CONTAGEIOUSNESS_BEGIN_STRAIN_1 1016
#define ED_CONTAGEIOUSNESS_END_STRAIN_1 1017
#define ED_CONTAGEIOUSNESS_BEGIN_STRAIN_2 1018
#define ED_CONTAGEIOUSNESS_END_STRAIN_2 1019
#define ED_INITIAL_CASES_STRAIN_1       1020
#define ED_IMMUNITY_REDUCTION_TIME      1021
#define ED_APPEARANCE_STRAIN_2          1022
#define ED_IMMUNITY_REDUCTION_DEGREE    1023
#define ED_INITIAL_CASES_STRAIN_2       1024
#define ED_NUMBER_OF_RUNS               1025
#define ED_OUTPUT_FILE_PREFIX           1026
#define ED_RANDOM_TRANSMISSION_PROBABILITY_STRAIN_3 1027
#define ED_RANDOM_TRANSMISSION_PROBABILITY_STRAIN_4 1028
#define IDC_CHECK1                      1030
#define IDC_EDIT1                       1031

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1032
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
